tap "cantino/mcfly", trusted: true
tap "coursier/formulas", trusted: true
tap "jandedobbeleer/oh-my-posh", trusted: true
tap "manaflow-ai/cmux", trusted: true
tap "ngrok/ngrok", trusted: true
tap "virtuslab/scala-cli", "https://github.com/Virtuslab/homebrew-scala-cli"
tap "yvgude/lean-ctx", trusted: true
brew "automake"
brew "azure-cli"
brew "bat"
brew "bpytop"
brew "cargo-llvm-cov"
brew "chezmoi"
brew "cmake"
brew "conan"
brew "dependency-check"
brew "dotnet"
brew "eza"
brew "fd"
brew "fzf"
brew "gcovr"
brew "gh"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "gnupg"
brew "go"
brew "gradle"
brew "helm"
brew "httpie"
brew "hugo"
brew "icu4c@75"
brew "jenv"
brew "lcov"
brew "mas"
brew "maven"
brew "mcfly"
brew "mono"
brew "ninja"
brew "nvm"
brew "openjdk@17"
brew "openjdk@21"
brew "pipx"
brew "pre-commit"
brew "prettyping"
brew "python-lsp-server"
brew "python-tk@3.14"
brew "rbenv"
brew "ripgrep"
brew "rtk"
brew "sbt"
brew "scala"
brew "snyk-cli"
brew "sonar-scanner"
brew "starship"
brew "thefuck"
brew "tldr"
brew "trivy"
brew "typescript-language-server"
brew "uv"
brew "zoxide"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "coursier/formulas/coursier", trusted: true
brew "yvgude/lean-ctx/lean-ctx", link: false, trusted: true
cask "1password-cli"
cask "alt-tab"
cask "claude-code@latest"
cask "cmux"
cask "copilot-cli"
cask "corretto"
cask "flameshot"
cask "ghostty"
cask "hiddenbar"
cask "meetingbar"
cask "postman"
cask "raycast"
mas "CyberhavenExtensionHost", id: 1619117350
mas "Magnet", id: 441258766
vscode "anthropic.claude-code"
vscode "davidkol.fastcompare"
vscode "docker.docker"
vscode "foam.foam-vscode"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "mechatroner.rainbow-csv"
vscode "mohsen1.prettify-json"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.makefile-tools"
vscode "redhat.vscode-yaml"
vscode "sonarsource.sonarlint-vscode"
vscode "twxs.cmake"
vscode "vscjava.vscode-maven"
vscode "yzhang.markdown-all-in-one"
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"
