version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ if .SSHSession }} {{ .UserName }} {{ end }}'
    background = 'p:yellow'
    foreground = 'p:black'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    leading_diamond = ''
    powerline_symbol = ''
    template = ' {{ if not .Writable }}{{ end}}  {{ path .Path .Location }} '
    background = 'p:orange'
    foreground = 'p:black'

    [blocks.segments.properties]
      style = 'agnoster_short'
      folder_icon = " \uf07b "
      hone_icon = "\ue617"
      mapped_locations_enabled = true

      [blocks.segments.properties.mapped_locations]
        "~/git/" = "\uF09B "

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:purple{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    background = 'p:blue'
    foreground = 'p:black'

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    background = 'p:green'
    foreground = 'p:white'

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    type = "aws"
    style = "diamond"
    leading_diamond = ''
    trailing_diamond = ''
    foreground = "#ffffff"
    background = "#FFA400"
    template = "  {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"

  [[blocks.segments]]
    type = "terraform"
    style = "diamond"
    leading_diamond = ''
    trailing_diamond = ''
    foreground = "#000000"
    background = "#ebcc34"
    template = "{{.WorkspaceName}}"

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    template = '  '
    background = 'p:red'
    foreground = 'p:white'

  [[ blocks.segments]]
    type = "ruby"
    style = "plain"
    foreground = "#ffffff"
    background = "#4063D8"
    template = "  {{ .Full }}"

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    template = ' {{ .Full }}'
    background = 'transparent'
    foreground = 'p:green'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    template = ' {{ .Full }}'
    background = 'transparent'
    foreground = 'p:blue'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'php'
    style = 'plain'
    template = '  {{ .Full }}'
    background = 'transparent'
    foreground = 'p:orange'

  [[blocks.segments]]
    type = 'dotnet'
    style = 'plain'
    template = '  {{ .Full }}'
    background = 'transparent'
    foreground = 'p:red'


  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    template = '  {{ .Full }}'
    background = 'transparent'
    foreground = 'p:yellow'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false
      fetch_virtual_env = false

  [[blocks.segments]]
    type = "kubectl"
    style = "plain"
    foreground = "#000000"
    background = "#ebcc34"
    template = " ﴱ {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} "

  [[blocks.segments]]
    type = "helm"
    style = "plain"
    background = "#a7cae1"
    foreground = "#100e23"
    powerline_symbol = ""
    template = " Helm {{ .Version }}"

  [[blocks.segments]]
    type = "upgrade"
    style = "plain"
    foreground = "#111111"
    background = "#FFD664"

[[tooltips]]
  type = 'aws'
  tips = ['aws']
  style = 'diamond'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  background = 'p:orange'
  foreground = 'p:white'

  [tooltips.properties]
    display_default = true

[[tooltips]]
  type = 'az'
  tips = ['az']
  style = 'diamond'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '
  background = 'p:blue'
  foreground = 'p:white'

  [tooltips.properties]
    display_default = true

[transient_prompt]
  template = '<p:yellow,transparent></><,p:yellow> {{ .PWD }} </><p:yellow,transparent></> '
  background = 'transparent'
  foreground = 'p:black'

[secondary_prompt]
  template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
  background = 'transparent'
  foreground = 'p:black'

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'
  purple = '#CF9FFF'
